{% set name = "libnvme" %}
{% set version = "1.16.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/linux-nvme/{{ name }}/archive/refs/tags/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  md5: a6554fb50022d762021fc1e949e01520

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - meson
    - ninja
    # just to make dependency versions build and host identical
    - json-c >=0.13
    - keyutils
    - openssl >=1.1.0
    - pkg-config
    - python
    - swig
  host:
    - json-c >=0.13
    - keyutils
    - openssl >=1.1.0
    - pkg-config
    - python
    - swig
  run:
    - python
    - json-c
    - keyutils
    - openssl

test:
  requires:
    - pkg-config
  imports:
    - libnvme
  commands:
    - test -f "${PREFIX}/include/libnvme.h"
    - test -f "${PREFIX}/lib/libnvme.so"
    - pkg-config --exists libnvme
    - python -c "import sys; from libnvme import nvme"

about:
  home: https://github.com/linux-nvme/libnvme
  summary: This is the libnvme development C library.
  license: LGPL-2.1
  license_file:
    - COPYING

extra:
  recipe-maintainers:
    - Geertsky
