{% set name = "blivet" %}
{% set version = "3.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/blivet-{{ version }}.tar.gz
  sha256: 782894492153bae67a8219df08fd18c92db3eca5bf8a17ac8e3c7c32a24d6758

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
requirements:
  host:
    - pip
    - setuptools
    - wheel
    - python
  run:
    - libblockdev
    - libbytesize
    - dasbus
    - packaging
    - lvm2
    - util-linux
    - pygobject
    - pyparted
    - python
    - pyudev
test:
  imports:
    - blivet
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/storaged-project/blivet
  summary: Python module for system storage configuration
  license: GPL-2.0 AND LGPL-2.1
  license_file:
    - COPYING
    - COPYING.LESSER

extra:
  recipe-maintainers:
    - Geertsky
