# ------------------------------------------------
package:
    name: kmod
    version: "34.2"
build:
  number: 1
  run_exports:
    - {{ pin_subpackage('kmod', max_pin='x') }}

source:
  url: https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-34.2.tar.gz
  md5: c34c4d5566bd69b1972879ff5498979a
requirements:
  build:
    - meson
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    - pkg-config
    - ninja

  host:
    - openssl
    - xz
    - zlib
    - zstd

test:
  commands:
    - depmod   --help
    - insmod   --help
    - kmod     --help
    - lsmod    --help
    - modinfo  --help
    - modprobe --help
    - rmmod    --help
    - test -f "${PREFIX}"/lib/libkmod.so
    - test -f "${PREFIX}"/include/libkmod.h
about:
  home: https://github.com/kmod-project/kmod
  summary: kmod is a set of tools to handle common tasks with Linux kernel modules like insert, remove, list, check properties, resolve dependencies and aliases.
  license: GPL-2.0 AND LGPL-2.1
  license_file:
    - COPYING

extra:
  recipe-maintainers:
    - Geertsky
